name: create terraform remote state

on:
  workflow_dispatch:

  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    GH_PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  create_tf_rm_st:
    runs-on: ubuntu-latest

  steps:
  - name: Checkout Git Repository
  - uses: actions/checkout@v4

  - name: Create S3 Bucket
      run: |
        echo "BUCKET_NAME="tf-rm-st-bkt-$(echo $RANDOM | md5sum | head -c 7)" >> $GITHUB_ENV
        aws s3api create-bucket --bucket ${{ env.BUCKET_NAME }} --region ${{ AWS_DEFAULT_REGION }}

  - name: Put Bucket Versioning
      run: |
        aws s3api put-bucket-versioning --bucket ${{ env.BUCKET_NAME }} --versioning-configuration Status=Enabled

  - name: Put Bucket Encryption
      run: |
        aws s3api put-bucket-encryption --bucket ${{ BUCKET_NAME }} --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'

  - name: Create Dynamodb Table
      run: |
        echo TABLE_NAME="tf-rm-st-tbl-$(echo ${{ env.BUCKET_NAME }} | awk -F '-' '{print $5}')"
        aws dynamodb create-table --table-name ${{ env.TABLE_NAME }} --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST

  - name: Update Terraform Modules
      run: |
        sed -i "s/\"[a-z][a-z]-[a-z].*-[0-9]\"/\"${{ secrets.AWS_REGION }}\"/g" main.tf
        sed -i "s/\"tf-rm-st-bkt.*\"/\"${{ env.BUCKET_NAME }}\"/g" main.tf 
        sed -i "s/\"tf-rm-st-tbl.*\"/\"${{ env.TABLE_NAME }}\"/g" main.tf

  - name: Update Git Repository
      run: |
        git config --local user.email ""
        git config --local user.email ""
        git commit -a -m "updating tf remote state"
      uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT_TOKEN }}
          repository: dev/dev
          force_with_lease: true
